# Generated by Django 4.2.6 on 2023-11-08 09:39

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    admin_group = Group(name="admin")
    admin_group.save()
    curator_group = Group(name="curator")
    curator_group.save()


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["admin", "curator"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
