# Generated by Django 4.2.6 on 2024-08-28 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0010_alter_decision_workflow_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflowticket",
            old_name="workflow_id",
            new_name="workflow",
        ),
    ]
