# Generated by Django 4.2.6 on 2024-05-22 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0005_workflowticket_ticket_type_alter_workflow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="url",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
