# Generated by Django 4.2.6 on 2024-06-17 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0006_workflow__created_at_workflow__updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="is_update",
        ),
    ]
